# This is a basic workflow to help you get started with Actions

name: Waka Readme

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.10
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
